version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kubernetes-singleton:latest
    container_name: singleton-app
    volumes:
      - ./config:/config
    environment:
      - POD_NAMESPACE=default
    ports:
      - "4000:80"
    deploy:
      replicas: 3
    restart: always
